mshop/routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (){
    auth('clients')->logout();
    return 'INDEX';
})->name('front.index');



Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth']
], function(){
    //Auth::logout();

    Route::group([
        'middleware' => ['admin']
    ], function () {
        Route::get('/', 'DashboardController')->name('dashboard');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/products', 'ProductController');
        Route::resource('/orders', 'OrderController');
        Route::group([
            'prefix' => 'clients',
            'as' => 'clients.'
        ], function () {
            Route::get('/get-clients', 'ClientController@getClients')->name('get-clients');
        });
        Route::resource('/clients', 'ClientController');
    });

    Route::get('/products', 'ProductController@index')->name('products.index');
    Route::get('/products/{product}', 'ProductController@show')->name('products.show');

});





Auth::routes();

// Client Auth Routes

Route::get('/clients/register', 'Auth\RegisterController@clientRegisterForm')->name('client-register-form');
Route::post('/clients/register', 'Auth\RegisterController@registerClient')->name('register-client');
Route::get('/clients/login', 'Auth\LoginController@clientLoginForm')->name('client-login-form');
Route::post('/clients/login', 'Auth\LoginController@clientLogin')->name('client-login');
Route::get('/clients/logout', 'Auth\LoginController@clientLogout')->name('client-logout');

mshop/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'description',
        'parent_id',
        'level',
    ];

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

}

mshop/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;
use App\Repository\Category\CategoryRepositoryInterface;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;


class CategoryController extends Controller
{
    private $categoryRepository;

    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }
            
    /**
     * Display a listing of the resource. 
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       // if (!$request->user()->is_admin) {
      //                  abort(403);
     //       }
            
        return view('admin.category.index' , [
            'categories' => $this->categoryRepository->paginate($request)
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create' , [
            'categories' => $this->categoryRepository->all()
        ]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     * @param  CategoryRequest  $request
     */
    public function store(CategoryRequest $request)
    {
        $category = $this->categoryRepository->create($request);

        return redirect(route('admin.categories.show' , $category));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.category.show', [
                'category'=> $category
        ]); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit',[
            'category' => $category,
            'categories' => Category::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     * @param  CategoryRequest  $request
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $request = $this->levelHandle($request);
        
        $category->update($request->all());
        return redirect(route('admin.categories.show', $category));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return  redirect(route('admin.categories.index'));

    }

    

}

mshop/resources/views/admin/category/create.blade.php
@extends('layouts.app')

@section('title', 'All Categories')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categories</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.categories.index')}}">Categories </a></li>
              <li class="breadcrumb-item active">Create New Category</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <form action="{{route('admin.categories.store')}}", method="post">
                  @include('admin.category.form')
              </form>
                 
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

mshop/resources/views/admin/category/edit.blade.php
@extends('layouts.app')

@section('title', 'All Categories')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categories</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.categories.index')}}">Categories </a></li>
              <li class="breadcrumb-item active">Create New Category</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <form action="{{route('admin.categories.update', $category)}}", method="post">
                  @method('PUT')
                  @include('admin.category.form')
              </form>
                 
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

mshop/resources/views/admin/category/form.blade.php
@csrf
                  <div class="form-group">
                      <label for="parent_id">Parent Category</label>
                      <select name="parent_id" id="parent_id" class="form-control">
                          <option value="">not set</option>
                          @foreach($categories as $rowCategory)
                            @if(isset($category) && $category->parent && $rowCategory->id == $category->parent->id)
                                <option value="{{ $rowCategory->id }}" selected>{{ $rowCategory->name }}</option>
                            @else
                                <option value="{{ $rowCategory->id }}">{{ $rowCategory->name }}</option>
                            @endif
                        @endforeach

                      </select>
                      @if($errors->first('parent_id'))
                      <br>
                      <span class="alert alert-danger">
                            {{ $errors->first('parent_id')}}
                      </span>
                      @endif
                  </div>
                  <div class="form-group">
                      <label for="name">Name</label>
                      <input type="text" name="name" id="name" class="form-control" value="{{ isset($category)?$category->name : '' }}">
                      @if($errors->first('name'))
                      <br>
                      <span class="alert alert-danger">
                            {{ $errors->first('name')}}
                      </span>
                      @endif
                  </div>
                  <div class="form-group">
                      <label for="description">Description</label>
                      <textarea name="description" id="description" cols="30" rows="10" class="form-control">
                        {{ isset($category)?$category->description : '' }}
                      </textarea>
                      @if($errors->first('description'))
                      <br>
                      <span class="alert alert-danger">
                            {{ $errors->first('description')}}
                      </span>
                      @endif
                  </div>
                  <div class="text-center">
                      <button type="submit" class="btn btn-success">Save</button>
                  </div>

mshop/resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('title', 'All Categories')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categories</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item active">All Categories</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <div class="row">
                  <div class="col">
                        <form>
                        <select name="limit" id="">
                            <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                            <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                            <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                        </select>
                        <button type="submit"> Update</button>
                    </form>
                  </div>
                  
                  <div class="col text-center">
                  <form action="">
                        <input type="text" name="search" class="form-control">
                        <button type="submit" class="btn btn-info">Searching</button>
                         <a href="{{route('admin.categories.index')}}">Reset</a>   
                    </form>
                  </div>
                  <div class="col text-right">
                      <a href="{{route('admin.categories.create')}}" class="btn btn-success">create</a>
                  </div>
              </div>
              
          <table class="table table-bordered">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>name</th>
                      <th>Parent</th>
                      <th>Actions</th>
                  </tr>
              </thead>
              <tbody>
                  @foreach($categories as $category)
                  <tr>
                      <td>{{ $category->id }}</td>
                      <td>{{ $category->name }}</td>
                      <td>
                            @if ($category->parent)
                                <a href="{{ route('admin.categories.show', $category->parent) }}" class="link-item">{{ $category->parent->name }}</a>
                             @endif
                      </td>
                      <td>
                         <a href="{{route('admin.categories.show', $category)}}" class="btn btn-info">Show</a>
                         <a href="{{route('admin.categories.edit', $category)}}" class="btn btn-primary">Edit</a>
                         <form action="{{ route('admin.categories.destroy', $category) }}" method="post" class="d-inline-block">
                                      @csrf
                                      @method('DELETE')
                                      <button type="submit" class="btn btn-danger">Delete</button>
                          </form>
                      </td>
                  </tr>
                  @endforeach
              </tbody>
          </table>
          {!! $categories->links() !!}
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

mshop/resources/views/admin/category/show.blade.php
@extends('layouts.app')

@section('title', 'All Categories')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categories</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.categories.index')}}">Categories </a></li>
              <li class="breadcrumb-item active">Show Category: {{$category->name}}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">

        <div class="row">
          <div class="card card-body">
              <h2>Title:<br> {{$category->name}}</h2>
              <p>Desciption: <br> {{$category->description}}</p>
              @if($category->parent)
                Parent: <a href="{{route('admin.categories.show', $category->parent)}}">{{$category->parent->name}}</a>
              @endif
                 <a href="{{route('admin.categories.edit', $category)}}" class="btn btn-primary">Edit</a>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection