mshop/routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (){
    auth('clients')->logout();
    return 'INDEX';
})->name('front.index');



Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth']
], function(){
    //Auth::logout();

    Route::group([
        'middleware' => ['admin']
    ], function () {
        Route::get('/', 'DashboardController')->name('dashboard');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/products', 'ProductController');
        Route::resource('/orders', 'OrderController');
        Route::group([
            'prefix' => 'clients',
            'as' => 'clients.'
        ], function () {
            Route::get('/get-clients', 'ClientController@getClients')->name('get-clients');
        });
        Route::resource('/clients', 'ClientController');
    });

    Route::get('/products', 'ProductController@index')->name('products.index');
    Route::get('/products/{product}', 'ProductController@show')->name('products.show');

});





Auth::routes();

// Client Auth Routes

Route::get('/clients/register', 'Auth\RegisterController@clientRegisterForm')->name('client-register-form');
Route::post('/clients/register', 'Auth\RegisterController@registerClient')->name('register-client');
Route::get('/clients/login', 'Auth\LoginController@clientLoginForm')->name('client-login-form');
Route::post('/clients/login', 'Auth\LoginController@clientLogin')->name('client-login');
Route::get('/clients/logout', 'Auth\LoginController@clientLogout')->name('client-logout');

mshop/app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\Hash;


class Client extends User
{
    protected $fillable =[
        'name',
        'email',
        'password'
    ];

    public function setPasswordAttribute($plainPassword)
    {
        $this->attributes['password'] = Hash::make($plainPassword);
    }

}

mshop/app/Http/Controllers/API/V1/ClientController.php
<?php

namespace App\Http\Controllers\API\V1;

use AElnemr\RestFullResponse\CoreJsonResponse;
use App\Client;
use App\Http\Controllers\Controller;
use App\Http\Resources\ClientList;
use App\Http\Resources\ClientShow;

use Illuminate\Http\Request;

class ClientController extends Controller
{
    use CoreJsonResponse;

    public function index()
    {
        $clients = ClientList::collection(Client::all());
        return $this->ok($clients->resolve());
      
    }

    public function show(Client $client)
    {
        return new ClientShow($client);
    }


}

mshop/app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Order;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.client.index',[
            'clients'=> Client::query()->paginate(10)  
        ]);
    }

    public function getClients(Request $request)
    {
        return view('admin.client.table', [
            'clients' => Client::query()->paginate(10)
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return 'deleted';
    }
}

mshop/resources/views/admin/client/index.blade.php
@extends('layouts.app')

@section('title', 'All Clients')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Categories</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item active">All Clients</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <div class="row">
                  <div class="col">
                        <form>
                        <select name="limit" id="">
                            <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                            <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                            <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                        </select>
                        <button type="submit"> Update</button>
                    </form>
                  </div>
                  
                  <div class="col text-center">
                  <form action="">
                        <input type="text" name="search" class="form-control">
                        <button type="submit" class="btn btn-info">Searching</button>
                         <a href="{{route('admin.clients.index')}}">Reset</a>   
                    </form>
                  </div>
                  <div class="col text-right">
                      <a href="{{route('admin.clients.create')}}" class="btn btn-success">create</a>
                  </div>
              </div>
              
          <table class="table table-bordered table-data">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>name</th>
                      <th>email</th>
                      
                  </tr>
              </thead>
              <tbody>
                  @foreach($clients as $client)
                  <tr>
                      <td>{{ $client->id }}</td>
                      <td>{{ $client->name }}</td>
                      <td>{{ $client->email }}</td>
                      
                      <td>
                         <a href="{{route('admin.clients.show', $client)}}" class="btn btn-info">Show</a>
                         <a href="{{route('admin.clients.edit', $client)}}" class="btn btn-primary">Edit</a>
                         <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.clients.destroy', $client) }}">Delete</button>
                            
                      </td>
                  </tr>
                  @endforeach
              </tbody>
          </table>
            
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

@section('js')
    <script>


        $(function(){
              getAllClients();
        })
        
        $(document).on('click', '.delete', function(e){
            //e.preventDefault();
            Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                    }).then((result) => {
                        if (result.isConfirmed) {
                         
                         //$(`#delete-${$(this).data('id')}`).submit();

                         $.ajax({
                             url: $(this).data('url'),
                             type: 'POST',
                             data: {
                                 _method : 'DELETE',
                                 _token : '{{ csrf_token() }}'
                             },
                             success: function(res){
                                    //console.log('res');
                                    if (result.value) {
                                            Swal.fire(
                                            'Deleted!',
                                            'Your file has been deleted.',
                                            'success'
                                            );
                                            getAllClients();
                                        }
                             }
                         });

                        //$.ajax({
                        //    url: '{{route('admin.categories.show', 1)}}',
                        //    type: 'GET',
                        //    success: function(res){
                        //        console.log(res);
                        //    }
                        //})
                    }
                })

        })

    $(document).on('click', '.page-link', function (e) {
        e.preventDefault();
        getAllClients($(this).text())
    });
    

    function getAllClients(page = 1) {
            $.ajax({
                url: '{{ route('admin.clients.get-clients') }}?page=' + page,
                type: 'GET',
                success: function (res) {
                    $('.table-data tbody').html(res);
                }
            })
        }
    

        
    </script>
    
@endsection

mshop/resources/views/admin/client/table.blade.php
@foreach($clients as $client)
    <tr>
        <td>{{ $client->id }}</td>
        <td>{{ $client->name }}</td>
        <td>{{ $client->email }}</td>
        <td>
            <a href="{{route('admin.clients.show', $client)}}" class="btn btn-info">Show</a>
            <a href="{{route('admin.clients.edit', $client)}}" class="btn btn-primary">Edit</a>
            <button type="button" class="btn btn-danger delete" data-url="{{ route('admin.clients.destroy', $client) }}">Delete</button>
        </td>
    </tr>
@endforeach

<tr>
    <td colspan="4">{!! $clients->links() !!}
    </td>
</tr>