mshop/routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (){
    auth('clients')->logout();
    return 'INDEX';
})->name('front.index');



Route::group([
    'prefix' => '/admin',
    'as' => 'admin.',
    'middleware' => ['auth']
], function(){
    //Auth::logout();

    Route::group([
        'middleware' => ['admin']
    ], function () {
        Route::get('/', 'DashboardController')->name('dashboard');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/products', 'ProductController');
        Route::resource('/orders', 'OrderController');
        Route::group([
            'prefix' => 'clients',
            'as' => 'clients.'
        ], function () {
            Route::get('/get-clients', 'ClientController@getClients')->name('get-clients');
        });
        Route::resource('/clients', 'ClientController');
    });

    Route::get('/products', 'ProductController@index')->name('products.index');
    Route::get('/products/{product}', 'ProductController@show')->name('products.show');

});





Auth::routes();

// Client Auth Routes

Route::get('/clients/register', 'Auth\RegisterController@clientRegisterForm')->name('client-register-form');
Route::post('/clients/register', 'Auth\RegisterController@registerClient')->name('register-client');
Route::get('/clients/login', 'Auth\LoginController@clientLoginForm')->name('client-login-form');
Route::post('/clients/login', 'Auth\LoginController@clientLogin')->name('client-login');
Route::get('/clients/logout', 'Auth\LoginController@clientLogout')->name('client-logout');

mshop/app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable =[
        'date',
        'client_id',
        'user_id',
        'total_amount'
        

    ];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class,
                'order_details', 
                'order_id', 
                'product_id')
                ->withPivot(['price', 'quantity', 'total'])
                ->withTimestamps();
    }
}

mshop/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderRequest;
use App\Order;
use App\Client;
use App\Product;
use App\Repository\Order\OrderRepositoryInterface;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function __construct(OrderRepositoryInterface $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return  view('admin.order.index', [
            'orders' => $this->orderRepository->paginate($request)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
            
        return view('admin.order.create',[
            'products' => Product::all(),
            'clients' => Client::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {   
        $order = $this->orderRepository->create($request);

        return redirect(route('admin.orders.show', $order));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

mshop/resources/views/admin/order/create.blade.php
@extends('layouts.app')

@section('title', 'All Orders')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Orders</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">admin </a></li>
              <li class="breadcrumb-item"><a href="{{route('admin.orders.index')}}">Orders </a></li>
              <li class="breadcrumb-item active">Create New Order</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="card card-body">
              <form action="{{route('admin.orders.store')}}", method="post">
                  @include('admin.order.form')
              </form>
                 
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
@endsection

mshop/resources/views/admin/order/form.blade.php
@csrf
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="client_id">Client Name</label>
            <select name="client_id" id="client_id" class="form-control">
                @foreach($clients as $client)
                    <option value="{{ $client->id }}"
                        {{ old('client_id') == $client->id ? 'selected' : '' }}>
                        {{ $client->name }}
                    </option>
                @endforeach
            </select>
            @if ($errors->first('client_id'))
                <span class="text-danger">
          {{ $errors->first('client_id') }}
        </span>
            @endif

        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label for="date">Order Date</label>
            <input type="date" id="date" name="date" class="form-control" value="{{ old('date') }}">
            @if ($errors->first('date'))
                <span class="text-danger">
                  {{ $errors->first('date') }}
                </span>
            @endif

        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <h3>Products
            @if ($errors->first('products'))
                <span class="text-danger">
                  {{ $errors->first('products') }}
                </span>
            @endif

        </h3>

        <button type="button" class="btn btn-info" id="btn-add-new-product">Add Product</button>
    </div>
    <table class="table mt-3">
        <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody id="products-list">

        @if (old('products'))
            @foreach(old('products') as $rowId => $rowProduct)
                <tr id="product-{{$rowId}}">
                    <td>
                        <select name="products[{{$rowId}}][product_id]"
                                class="form-control input-product-product_id"
                                row-id="product-{{$rowId}}">
                            @foreach($products as $product)
                                @if ($product->id == $rowProduct['product_id'])
                                    <option value="{{ $product->id }}" selected data-price="{{ $product->price }}">
                                        {{ $product->name }} | {{ $product->price }}
                                    </option>
                                @else
                                    <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                                        {{ $product->name }} | {{ $product->price }}
                                    </option>
                                @endif
                            @endforeach
                        </select>

                        @if ($errors->first('products.' . $rowId . '.product_id'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.product_id') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <input type="number"
                               name="products[{{$rowId}}][quantity]"
                               value="{{ $rowProduct['quantity']?? 1 }}"
                               row-id="product-{{$rowId}}"
                               class="form-control input-product-quantity">
                        @if ($errors->first('products.' . $rowId . '.quantity'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.quantity') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <input type="number"
                               name="products[{{$rowId}}][price]"
                               readonly
                               class="form-control input-product-price"
                               row-id="product-{{$rowId}}"
                               value="{{ $rowProduct['price']?? 1 }}">
                        @if ($errors->first('products.' . $rowId . '.price'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.price') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <input type="number"
                               name="products[{{$rowId}}][total]"
                               readonly
                               class="form-control input-product-total"
                               row-id="product-{{$rowId}}"
                               value="{{ $rowProduct['total'] == 0 ? $rowProduct['price'] : $rowProduct['total'] }}">

                        @if ($errors->first('products.' . $rowId . '.total'))
                            <span class="text-danger">
                              {{ $errors->first('products.' . $rowId . '.total') }}
                            </span>
                        @endif
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger row-delete" row-id="product-{{$rowId}}">-</button>
                    </td>
                </tr>
            @endforeach
        @else
            <tr id="product-1">
                <td>
                    <select name="products[1][product_id]"
                            class="form-control input-product-product_id"
                            row-id="product-1">
                        @foreach($products as $product)
                            <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                                {{ $product->name }} | {{ $product->price }}
                            </option>
                        @endforeach
                    </select>
                </td>
                <td>
                    <input type="number"
                           name="products[1][quantity]"
                           value="1"
                           row-id="product-1"
                           class="form-control input-product-quantity">
                </td>
                <td>
                    <input type="number"
                           name="products[1][price]"
                           readonly
                           class="form-control input-product-price"
                           row-id="product-1"
                           value="{{ $products->first()->price }}">
                </td>
                <td>
                    <input type="number"
                           name="products[1][total]"
                           readonly
                           class="form-control input-product-total"
                           row-id="product-1"
                           value="{{ $products->first()->price }}">
                </td>
                <td>
                    <button type="button" class="btn btn-danger row-delete" row-id="product-1">-</button>
                </td>
            </tr>
        @endif

        </tbody>

    </table>
</div>
<div class="text-center">
    <button type="submit" class="btn btn-success">Save</button>
</div>
@section('js')
    <script>

        /**
         * Events
         */
        $(document).on('click', '#btn-add-new-product', function () {
            const rowId = Date.now();
            const productRow = `
            <tr id="product-${rowId}">
                <td>
                    <select name="products[${rowId}][product_id]"
                    row-id="product-${rowId}"
                    class="form-control  input-product-product_id">
                        @foreach($products as $product)
                            <option value="{{ $product->id }}" data-price="{{ $product->price }}">
                                {{ $product->name }} | {{ $product->price }}
                            </option>
                        @endforeach
                    </select>
                </td>
                <td>
                    <input type="number"
                    name="products[${rowId}][quantity]"
                    value="1"
                    row-id="product-${rowId}"
                    class="form-control input-product-quantity">
                </td>
                <td>
                    <input type="number"
                    name="products[${rowId}][price]"
                    row-id="product-${rowId}"
                    value="{{ $products->first()->price }}"
                    readonly
                    class="form-control input-product-price">
                </td>
                <td>
                    <input type="number"
                    name="products[${rowId}][total]"
                    row-id="product-${rowId}"
                    readonly
                    value="{{ $products->first()->price }}"
                    class="form-control input-product-total">
                </td>
                <td>
                    <button type="button" class="btn btn-danger row-delete" row-id="product-${rowId}">-</button>
                </td>
            </tr>
            `;
            $('#products-list').append(productRow);
        });

        $(document).on('click', '.row-delete', function () {
            const rowId = '#' + $(this).attr('row-id');
            $(rowId).remove();
        });

        $(document).on('keyup', '.input-product-quantity', function () {
            const rowId = '#' + $(this).attr('row-id');
            calculateTotal(rowId);
        });

        $(document).on('change', '.input-product-product_id', function () {
            const rowId = '#' + $(this).attr('row-id'),
                price = $(this).children("option:selected").data('price')
            ;
            $(`${rowId} .input-product-price`).val(price);
            calculateTotal(rowId);
        });

        ///////////////////////////
        /**
         * Functions
         */

        /**
         * @param rowId
         */
        function calculateTotal(rowId) {
            const quantity = $(`${rowId} .input-product-quantity`).val(),
                price = $(`${rowId} .input-product-price`).val(),
                total = price * quantity;

            $(`${rowId} .input-product-total`).val(total);
        }
    </script>
@endsection

mshop/resources/views/admin/order/index.blade.php
@extends('layouts.app')

@section('title', 'All Orders')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Orders</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">admin</a></li>
                            <li class="breadcrumb-item active">All Orders</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <div class="row">
                            <div class="col">
                                <form>
                                    <select name="limit" id="">
                                        <option value="5" {{ Request::get('limit') == 5? 'selected' : '' }}>5</option>
                                        <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                                        <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                                    </select>
                                    <button type="submit">update</button>
                                </form>
                            </div>
                            <div class="col text-center">
                                <form>
                                    <input type="text" name="search" class="form-control">
                                    <button type="submit" class="btn btn-info">Searching</button>
                                    <a href="{{ route('admin.orders.index') }}">Reset</a>
                                </form>
                            </div>
                            <div class="col text-right">
                                <a href="{{ route('admin.orders.create') }}" class="btn btn-success">Create</a>
                            </div>
                        </div>



                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Client Name</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($orders as $order)
                                <tr>
                                    <td>{{ $order->id }}</td>
                                    <td>{{ $order->client->name }}</td>
                                    <td>
                                        <a href="{{ route('admin.orders.show', $order) }}" class="btn btn-info">Show</a>
                                        <a href="{{ route('admin.orders.edit', $order) }}" class="btn btn-primary">Edit</a>
                                        <form action="{{ route('admin.orders.destroy', $order) }}" method="post" class="d-inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                        <div class="text-right">
                      
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
@endsection